services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: lab10
      POSTGRES_USER: lab10
      POSTGRES_PASSWORD: lab10
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lab10 -d lab10"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  postgres_data:
