name: (CI) [SysOp|AM2] PyLint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        git ls-files '*requirements.txt' | xargs -I {} pip install -r {}
    - name: Analysing the code with pylint
      run: |
        for root in am2 sysop; do
          pushd "$root"
          pylint $(git ls-files '*.py')
          popd
        done
